// import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import EventListener from "~/components/event-listener";
import WalletConnectButton from "~/components/wallet-connect-btn";

// import { api } from "~/utils/api";

export default function Home() {
  // const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <nav className="flex w-full items-center justify-end p-3 ring">
          <WalletConnectButton />
        </nav>
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Create <span className="text-[hsl(280,100%,70%)]">T3</span> App
          </h1>
          <div className="my-8 w-full rounded-md p-4 text-white ring ring-white">
            <EventListener />
          </div>
        </div>
      </main>
    </>
  );
}
